GRAPH:: TRANSITION+
TRANSITION:: STATE --> [STATE | STATE DESCRIPTION] "\n"
STATE:: NAME | NAME DESCRIPTION
NAME:: SYMBOL | DELIMITER
SYMBOL:: [A-Za-z\_][A-Za-z0-9\_\-]*
DELIMITER:: "\[\*\]"
DESCRIPTION:: :DESC_TEXT
DESC_TEXT:: [a-zA-Z0-9\p]++
