.PHONY: test clean

header: 
	@echo "================== PKG =================="

all: header
	$(MAKE) -s  -C statemachine

test: header
	$(MAKE) -s -C statemachine test

clean: header
	$(MAKE) -s -C statemachine clean
